### ISSUE TITLE
Remove the model class argument from Relation

### ISSUE THREAD

**Issue by excitedleigh** [excitedleigh/bridgekeeper#3]
Currently, `Relation` has the signature `Relation(attribute_name, model_class, rule)`. Having the `model_class` argument is kind of a pain; ideally, `Relation` and `Attribute` should have matching signatures, and we should figure out the model class to construct a `QuerySet` from when `.query()` is called. (What would _really_ be ideal is if we could pass a `Q` object directly into `{attr}__in`, but Django doesn't let us do that.)

**Comment by adambrenecki** [comment]
`ManyRelation` is even uglier: it takes four args, when really it should just take two.

**Comment by excitedleigh** [comment]
[This message on django-developers](https://groups.google.com/forum/#!msg/django-developers/jEkCdzGnzRE/6lJQV4AqCwAJ) gives a function that adds a prefix to everything in a `Q` object, which should have the same effect as being able to go `Q(foo__in=Q(...))`.
