### ISSUE TITLE
The example for rules.ManyRelation is confusing

### ISSUE THREAD

**Issue by YukinoHayakawa** [excitedleigh/bridgekeeper#4]
```
perms['foo.view_customer'] = ManyRelation(
    'agencies', Agency, Is(lambda user: user.agency))
```
The example in the doc seems to miss the parameter query_attr. The model relationships involved in this example are also not very clear. If the ManyToManyField is defined in Customer and I check this permission against that model, does this mean that the permission is granted if any agency in Customer.agencies is matched with user.agency?

**Comment by YukinoHayakawa** [comment]
Or I think it means that the permission is granted when the only object filtered out from Customer.agencies by query_attr == user.agency?

**Comment by adambrenecki** [comment]
Yep, that's correct. Thanks for bringing the documentation error to my attention!

**Comment by excitedleigh** [comment]
I'm closing this because now that #3 is fixed, `ManyRelation` no longer takes those extra args anyway! Hooray!

Thanks again for checking out the project and reporting the error <3

**Comment by YukinoHayakawa** [comment]
> I'm closing this because now that #3 is fixed, `ManyRelation` no longer takes those extra args anyway! Hooray!
> 
> Thanks again for checking out the project and reporting the error <3

It has been a long time and I don't actually even understand my question now since I haven't been dealing with database since then : )
